# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-19 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0002_auto_20190517_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_rate', models.CharField(choices=[('1', '1*'), ('2', '2*'), ('3', '3*'), ('4', '4*'), ('5', '5*')], max_length=1)),
                ('comment', models.CharField(max_length=300)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forkilla.Restaurant')),
            ],
        ),
    ]
