# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-26 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0008_auto_20190526_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='featured_photo',
            field=models.ImageField(default='default.png', upload_to='forkilla/src/fotos'),
        ),
    ]
