# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-26 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0017_auto_20190526_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='featured_photo',
            field=models.ImageField(default='default.png', upload_to='forkilla/static/fotos'),
        ),
    ]
