# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-27 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0019_auto_20190527_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='featured_photo',
            field=models.ImageField(default='/fotos/default.png', upload_to='fotos/'),
        ),
    ]
